### ISSUE TITLE
Cannot install celocli. Error: EACCES: permission denied, access '/usr/local/lib'

### ISSUE THREAD

**Issue by regisd** [celo-org/wallet#50]
### Expected Behavior

Able to install celocli as documented

```
npm install -g @celo/celocli
```

### Current Behavior

```
ubuntu@ip-172-31-18-128:~$ npm install -g @celo/celocli
npm WARN checkPermissions Missing write access to /usr/local/lib
npm ERR! code EACCES
npm ERR! syscall access
npm ERR! path /usr/local/lib
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, access '/usr/local/lib'
npm ERR!  { [Error: EACCES: permission denied, access '/usr/local/lib']
npm ERR!   stack:
npm ERR!    'Error: EACCES: permission denied, access \'/usr/local/lib\'',
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/local/lib' }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2021-02-23T21_58_36_182Z-debug.log
```

**Comment by regisd** [comment]
I think instructions should not expect root access.

That being said, non-global installation also fails.

```
ubuntu@ip-172-31-18-128:~$ npm install @celo/celocli

> keytar@7.4.0 install /home/ubuntu/node_modules/@celo/celocli/node_modules/keytar
> prebuild-install || npm run build

prebuild-install WARN install libsecret-1.so.0: cannot open shared object file: No such file or directory

> keytar@7.4.0 build /home/ubuntu/node_modules/@celo/celocli/node_modules/keytar
> node-gyp rebuild

/bin/sh: 1: pkg-config: not found
gyp: Call to 'pkg-config --libs-only-l libsecret-1' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/nodejs/node-gyp/lib/configure.js:355:16)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 5.4.0-1037-aws
gyp ERR! command "/usr/bin/node" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/ubuntu/node_modules/@celo/celocli/node_modules/keytar
gyp ERR! node -v v10.19.0
gyp ERR! node-gyp -v v6.1.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! keytar@7.4.0 build: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the keytar@7.4.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2021-02-23T22_28_33_059Z-debug.log
```
